SELECT * FROM customer_behavior

-- q1 what is the total revenue generated by gender?
SELECT gender,
SUM(purchase_amount) as revenue
FROM customer_behavior
GROUP BY gender

-- q2 which customer used a discount but still spent more than the average purchase amount?
SELECT 
customer_id,
purchase_amount
FROM customer_behavior
WHERE discount_applied = 'Yes' and purchase_amount >= 
	(SELECT AVG(purchase_amount) FROM customer_behavior)

--q3 which are the top 5 product which the highest average review rating?
SELECT TOP 5
item_purchased,
ROUND(AVG(review_rating), 2) as avg_product_ratting
FROM customer_behavior
GROUP BY item_purchased
ORDER BY avg_product_ratting DESC
--OFFSET 0 ROWS FETCH NEXT 5 ROWS ONLY

-- q4 compare the average purchase amount betweens standard and express shipping
SELECT
shipping_type,
ROUND(AVG(purchase_amount), 2) as avg_purchase
FROM customer_behavior
WHERE shipping_type in ('Standard', 'Express')
GROUP BY shipping_type

-- q5 do subscribe customers spend more? compare average spend and
-- total revenue between subscribers and non-subscribers
SELECT
subscription_status,
COUNT(customer_id) AS total_customer,
AVG(purchase_amount) as avg_spend,
SUM(purchase_amount) AS total_revenue
FROM customer_behavior
GROUP BY subscription_status
ORDER BY total_revenue, avg_spend DESC

-- q6 which 5 product have highest percentage of purchase with discount applied
SELECT TOP 5
item_purchased,
ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*), 2) as discount_rate
FROM customer_behavior
GROUP BY item_purchased
ORDER BY discount_rate DESC

-- q7 segment customer inti new, returning, and loyal based on their total
-- number of previous purchase and show count each segment
with customer_type as (
	SELECT
	customer_id,
	previous_purchases,
	CASE WHEN previous_purchases = 1 THEN 'New'
		 WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
		 ELSE 'Loyal'
		 END AS customer_segment
	FROM customer_behavior
)

SELECT 
	customer_segment, 
	COUNT(*) AS [Number of Customers]
FROM customer_type
GROUP BY customer_segment
ORDER BY [Number of Customers] DESC

-- q8 what are the top 3 most purchased products whitin each category
WITH item_counts AS (
	SELECT 
	category,
	item_purchased,
	COUNT(customer_id) AS total_orders,
	ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
	FROM customer_behavior
	GROUP BY category, item_purchased
)
SELECT
item_rank,
category,
item_purchased,
total_orders
FROM item_counts
WHERE item_rank <= 3

-- q9 are customers who are repeat buyers (more than 5 previous pruchased) also likely to subscribe?
SELECT
subscription_status,
COUNT(customer_id) as repeat_buyers
FROM customer_behavior
WHERE previous_purchases > 5
GROUP BY subscription_status

-- q10 what is the revenue contribution of age group?
SELECT
age_group,
SUM(purchase_amount) as total_revenue
FROM customer_behavior
GROUP BY age_group
ORDER BY total_revenue DESC